[workspace]
members = [
    "bootloader-driver",
    "bootloader-tui",
]
resolver = "3"

[workspace.dependencies]
bootloader-tui = { path = "bootloader-tui" }
uefi = "0.35.0"
ratatui = { version = "0.30.0-alpha.4", default-features = false }
